//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyConverter.currencyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class convert
    {
        public int Id { get; set; }
        public string currency_from { get; set; }
        public string currency_to { get; set; }
        public decimal amount_from { get; set; }
        public decimal amount_to { get; set; }
        public System.DateTime convert_date { get; set; }
        public string comment { get; set; }
    
        public virtual currency currency { get; set; }
    }
}
