//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyConverter.currencyData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    

    public partial class ConvertDataEntities : DbContext
    {
        public ConvertDataEntities()
            : base("name=ConvertDataEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<convert> converts { get; set; }
        public virtual DbSet<currency> currencies { get; set; }
        public virtual DbSet<exchange_rates> exchange_rates { get; set; }

    }
}
